"""empty message

Revision ID: 922c7040a007
Revises: 
Create Date: 2024-12-24 15:29:19.058100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922c7040a007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('alpha2', sa.String(length=2), nullable=False),
    sa.Column('alpha3', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha2'),
    sa.UniqueConstraint('alpha3'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('country')
    # ### end Alembic commands ###
